local tbl = 
{
	
	{
		actions = 
		{
			
			{
				aType = 1,
				actionID = 11405,
				actionLua = "",
				allowInterrupt = true,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					5,
				},
				endIfUsed = true,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "BLU.Settings.Toggles[5].enable = enable\ndata.magicEnabled = false\nself.used = true\n",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					5,
				},
				endIfUsed = true,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Disable Magic",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "BLU.Settings.Toggles[5].enable = not enable\ndata.magicEnabled = true\nself.used = true\n",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					8,
					10,
				},
				endIfUsed = true,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Enable Magic",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return Player.job == 36",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "blu [true]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return Player.localmapid == 172\n",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "on aurum vale map [true]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = 1533,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "target is coincounter [true]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = 1534,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "target is locksmith [true]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 6,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
					3,
					4,
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = true,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "f: missile target",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "local t = MGetTarget(Player.id)\nif table.valid(t) then\n  return t.contentid ~= 1533\nend\nreturn false",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "target is coincounter [false]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return data.magicEnabled == true\n",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "magic enabled [true]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return data.magicEnabled ~= true\n",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "magic enabled [false]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "local t = MGetTarget(Player.id)\nif table.valid(t) then\n  return t.contentid ~= 1534\nend\nreturn false",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "target is locksmith [false]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 6,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
					6,
					9,
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "f: non-missile target",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1727,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Waning Nocturne [FALSE]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1718,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Waxing Nocturne [FALSE]",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "PG - BLU Aurum Vale",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 150,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "c570243f-9d43-de89-a5eb-63438e19ae5c",
	},
}



return tbl